spring:
  application:
    name: cloudBalance

  datasource:
    url: jdbc:mysql://localhost:3306/cloudBalance
    username: root
    password: YourPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secretKey: joiseju98uw94850w84309maskdmfoqur09mcaoidvnou9w8ut9